# Generated by Django 4.2.2 on 2023-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
