# Generated by Django 4.2.2 on 2023-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(max_length=500),
        ),
    ]
